routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('api')->group(function () {
    Route::get('/categories', 'Backend\CategoryController@apiIndex');
    Route::post('/categories/attribute', 'Backend\CategoryController@apiIndexAttribute');
});


Route::prefix('administrator')->group(function () {
    Route::get('/', 'Backend\MainController@masterPage');
    Route::resource('categories', 'Backend\CategoryController');
    Route::get('categories/{id}/settings','Backend\CategoryController@indexSetting')->name('categories.indexSettings');
    Route::post('categories/{id}/settings','Backend\CategoryController@saveSetting');
    Route::resource('attributes-group', 'Backend\AttributeGroupController');
    Route::resource('attributes-value', 'Backend\AttributesValueController');
    Route::resource('brands','Backend\BrandsController');
    Route::resource('photos','Backend\PhotosController');
    Route::post('photos/upload','Backend\PhotosController@upload')->name('photos.upload');
    Route::resource('products','Backend\ProductController');

});

resources/views/admin/attributes/create.blade.php
@extends('admin.layouts.master')


@section('main-content')

    <div class="box box-info colmd8">
        <div class="box-header with-border">
            <h2 class="box-title text-center">ایجاد ویژگی جدید</h2>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form method="post" action="{{url('administrator/attributes-group')}}">
                        {{@csrf_field()}}
                        <div class="form-group">
                            <label for="attribute-title">عنوان ویژگی :</label>
                            <input class="form-control" name="attribute-title" type="text"
                                   placeholder="عنوان گروه ویژگی را وارد کنید...">
                        </div>

                        <div class="form-group">
                            <label for="attribute-type">نوع ویژگی :</label>
                            <select class="form-control" name="attribute-type" id="">
                                <option value="select">لیست تکی</option>
                                <option value="multiple">لیست چندتایی</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-success pull-left">ذخیره</button>

                    </form>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/attributes/edit.blade.php
@extends('admin.layouts.master')


@section('main-content')

    <div class="box box-info colmd8">
        <div class="box-header with-border">
            <h2 class="box-title text-center">ویرایش ویژگی <b> (  {{$attributesGroup->title}}  )</b></h2>
        </div>
        <!-- /.box-header -->

        <div class="box-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form method="post" action="{{url('administrator/attributes-group/'.$attributesGroup->id)}}">
                        {{@csrf_field()}}
                        <input type="hidden" name="_method" value="PATCH">
                        <div class="form-group">
                            <label for="attribute-title">عنوان ویژگی :</label>
                            <input class="form-control" name="attribute-title" type="text" value="{{$attributesGroup->title}}"
                                   placeholder="عنوان گروه ویژگی را وارد کنید...">
                        </div>

                        <div class="form-group">
                            <label for="attribute-type">نوع ویژگی :</label>
                            <select class="form-control" name="attribute-type" id="" >
                                <option value="one" @if($attributesGroup->type == "seelect") selected @endif>لیست تکی</option>
                                <option value="multiple" @if($attributesGroup->type == "multiple") selected @endif>لیست چندتایی</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-success pull-left">ذخیره</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/attributes/index.blade.php
@extends('admin.layouts.master')


@section('main-content')

    <div class="col-md-12 main_content_ui">
        <div class="box box-info main_content_ui_shadow">
            <div class="box-header with-border">
                <h2 class="box-title text-center">ویژگی ها</h2>

                <a class="btn btn-app pull-left" href="{{route('attributes-group.create')}}"><i class="fa fa-plus"></i>
                    جدید</a>

            </div>
            @if (Session::has('attribute_sucsses'))
                <div class="alert alert-success">
                    <div>{{session('attribute_sucsses')}}</div>
                </div>


        @endif

        <!-- /.box-header -->
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <thead>
                        <tr>
                            <th class="text-primary">شناسه</th>
                            <th class="text-primary">عنوان</th>
                            <th class="text-primary">نوع</th>
                            <th class="text-primary">عملیات</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($attributesGroup as $attribute)
                            <tr>
                                <td>{{$attribute->id}}</td>
                                <td>{{$attribute->title}}</td>
                                <td>{{$attribute->type}}</td>
                                <div class="row">
                                    <td>
                                        <a class="btn btn-warning"
                                           href="{{route('attributes-group.edit',$attribute->id)}}">ویرایش</a>
                                        <div class="display_inline_block">
                                            <form method="post"
                                                  action="{{route('attributes-group.destroy',$attribute->id)}}">
                                                {{@csrf_field()}}
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-danger">حذف</button>
                                            </form>
                                        </div>
                                    </td>

                                </div>

                            </tr>
                        @endforeach

                        </tbody>
                    </table>

                    <div class="text-center ">
                        {{$attributesGroup->links()}}
                    </div>
                </div>
                <!-- /.table-responsive -->
            </div>

        </div>
    </div>

@endsection