routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('api')->group(function () {
    Route::get('/categories', 'Backend\CategoryController@apiIndex');
    Route::post('/categories/attribute', 'Backend\CategoryController@apiIndexAttribute');
});


Route::prefix('administrator')->group(function () {
    Route::get('/', 'Backend\MainController@masterPage');
    Route::resource('categories', 'Backend\CategoryController');
    Route::get('categories/{id}/settings','Backend\CategoryController@indexSetting')->name('categories.indexSettings');
    Route::post('categories/{id}/settings','Backend\CategoryController@saveSetting');
    Route::resource('attributes-group', 'Backend\AttributeGroupController');
    Route::resource('attributes-value', 'Backend\AttributesValueController');
    Route::resource('brands','Backend\BrandsController');
    Route::resource('photos','Backend\PhotosController');
    Route::post('photos/upload','Backend\PhotosController@upload')->name('photos.upload');
    Route::resource('products','Backend\ProductController');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function photo()
    {
        return $this->hasMany(photo::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brands::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class photo extends Model
{

    protected  $uploads = '/storage/photos/';
    public function brands()
    {
        return $this->belongsTo(Brands::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }

}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Brands;
use App\Category;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product:: paginate(10);
        return view('admin.products.index',compact(['products']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        $categories = Category::with('childrenRecursive')
//            ->where('parent_id',null)
//            ->get();
        $brands = Brands::all();
        return view('admin.products.create',compact(['brands']));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.master')

@section('dropzon_styles')
    <link rel="stylesheet" href="{{asset('/admin/dist/css/dropzone.css')}}">
@endsection

@section('main-content')

    <div class="box box-info colmd8" id="app">
        <div class="box-header with-border">
            <h2 class="box-title text-center">ایجاد برند جدید</h2>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form method="post" action="{{route('products.store')}}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="form-group">
                            <label for="title">نام محصول :</label>
                            <input class="form-control" type="text" name="title" placeholder="نام محصول را وارد کنید">
                        </div>
                        <div class="form-group">
                            <label for="title">نام مستعار :</label>
                            <input class="form-control" type="text" name="slug" placeholder="نام مستعار را وارد کنید">
                        </div>
                        <div class="form-group">
                            <label for="status">وضعیت نشر :</label>

                            <div>
                                <input type="radio" name="status" value="0" checked><span>منتشر نشده</span>
                                <input type="radio" name="status" value="1"><span>منتشر شده</span>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="title">قیمت محصول :</label>
                            <input class="form-control" type="number" name="price"
                                   placeholder="قیمت محصول را وارد کنید">
                        </div>
                        <div class="form-group">
                            <label for="title">قیمت ویژه محصول :</label>
                            <input class="form-control" type="number" name="price"
                                   placeholder="قیمت ویژه محصول را وارد کنید">
                        </div>
                        <div class="form-group">
                            <label for="description">توضیحات محصول :</label>
                            <textarea class="form-control" name="description" id="" cols="30" rows="7"
                                      placeholder="توضیحات محصول را وارد کنید"></textarea>
                        </div>
                        <attribute-component :brands="{{$brands}}"></attribute-component>
                        <div class="form-group">
                            <label>آپلود عکس :</label>
                            <div class="form-group">
                                <input type="hidden" name="photo_id" id="brand_photo">
                                <div id="photo" class="dropzone dropzone_ui"></div>
                            </div>

                        </div>
                        <div class="form-group">
                            <label>عنوان سئو :</label>
                            <input class="form-control" name="meta_title" type="text"
                                   placeholder="عنوان سئو را وارد کنید...">
                        </div>
                        <div class="form-group">
                            <label>توضیحات سئو :</label>
                            <textarea class="form-control" name="meta_desc" rows="7" type="text"
                                      placeholder="توضیحات سئو را وارد کنید..."></textarea>
                        </div>
                        <div class="form-group">
                            <label>کلمات کلیدی سئو :</label>
                            <input class="form-control" name="meta_keywords" type="text"
                                   placeholder="کلمات کلیدی سئو را وارد کنید...">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn  btn-success">ذخیره</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

@endsection
@section('script-vuejs')
    <script src="{{asset('admin/js/app.js')}}"></script>
@endsection
@section('dropzon_scripts')
    <script type="text/javascript" src="{{asset('/admin/dist/js/dropzone.js')}}"></script>
    <script>
        Dropzone.autoDiscover = false;
        uploadMultiple: false;
        addRemoveLinks: true;
        dictRemoveFile: 'Remove file';
        dictFileTooBig: 'Image is larger than 16MB';
        timeout: 10000;

        var drop = new Dropzone("#photo", {
            url: "{{route('photos.upload')}}",
            sending: function (file, xhr, formData) {
                formData.append("_token", "{{csrf_token()}}")
            },
            success: function (file, response) {
                document.getElementById('brand_photo').value = response.photo_id
            }
        })
    </script>



@endsection

resources/views/admin/products/edit.blade.php
@extends('admin.layouts.master')

@section('dropzon_styles')
    <link rel="stylesheet" href="{{asset('/admin/dist/css/dropzone.css')}}">
@endsection

@section('main-content')

    <div class="box box-info colmd8">
        <div class="box-header with-border">
            <h2 class="box-title text-center">ویرایش برند <b class="text-bold text-primary"> ( {{ $brand->title }} )</b></h2>
        </div>
        <!-- /.box-header -->

        <div class="box-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form method="post" action="{{url('administrator/brands/'.$brand->id)}}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="PATCH">
                        <div class="form-group">
                            <label for="description">تصویر برند :</label>
                            <div class="text-center">
                                <img src="{{asset($brand->photo->path)}}" class="img-fluid" width="280">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="title">نام برند :</label>
                            <input class="form-control" type="text" name="title" value="{{$brand->title}}">
                        </div>
                        <div class="form-group">
                            <label for="description">توضیحات برند :</label>
                            <textarea class="form-control" name="description" id="" cols="30" rows="7">{{$brand->description}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="upload">آپلود عکس :</label>
                            <div class="form-group">
                                <input type="hidden" name="photo_id" id="brand_photo" value="{{$brand->photo_id}}">
                                <div id="photo" class="dropzone dropzone_ui"></div>
                            </div>

                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn  btn-success">ذخیره</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

@endsection
@section('dropzon_scripts')
    <script type="text/javascript" src="{{asset('/admin/dist/js/dropzone.js')}}"></script>
    <script>
        Dropzone.autoDiscover = false;
        uploadMultiple: false;
        addRemoveLinks: true;
        dictRemoveFile: 'Remove file';
        dictFileTooBig: 'Image is larger than 16MB';
        timeout: 10000;

        var drop = new Dropzone("#photo", {
            url: "{{route('photos.upload')}}",
            sending: function (file, xhr, formData) {
                formData.append("_token", "{{csrf_token()}}")
            },
            success: function (file, response) {
                document.getElementById('brand_photo').value = response.photo_id
            }
        })

    </script>
@endsection

resources/views/admin/products/index.blade.php
@extends('admin.layouts.master')


@section('main-content')

    <div class="col-md-12 main_content_ui">
        <div class="box box-info main_content_ui_shadow">
            <div class="box-header with-border">
                <h2 class="box-title text-center">محصولات</h2>

                <a class="btn btn-app pull-left" href="{{route('products.create')}}"><i class="fa fa-plus"></i> جدید</a>

            </div>


            @if(Session::has('error_category'))
                <div class="alert alert-danger">
                    <div>{{session('error_category')}}</div>
                </div>

        @endif

        <!-- /.box-header -->
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <thead>
                        <tr>
                            <th class="text-primary">شناسه</th>
                            <th class="text-primary">کد محصول</th>
                            <th class="text-primary">عنوان</th>
                            <th class="text-primary">عملیات</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($products as $product)

                            <tr>
                                <td><span class="text">{{$product->id}}</span></td>
                                <td><span class="text">{{$product->sku}}</span></td>
                                <td><span class="text-bold">{{$product->title}}</span></td>
                                <div class="row">
                                    <td>
                                        <a class="btn btn-warning" href="{{route('products.edit',$product->id)}}">ویرایش</a>
                                        <div class="display_inline_block">
                                            <form method="post" action="{{url('administrator/products/'.$product->id)}}">
                                                {{@csrf_field()}}
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button type="submit" class="btn btn-danger">حذف</button>
                                            </form>
                                        </div>
                                    </td>

                                </div>
                            </tr>



                        @endforeach

                        </tbody>
                    </table>
                    <div class="text-center ">
                        {{$products->links()}}
                    </div>
                </div>
                <!-- /.table-responsive -->
            </div>

        </div>
    </div>

@endsection