routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('api')->group(function () {
    Route::get('/categories', 'Backend\CategoryController@apiIndex');
    Route::post('/categories/attribute', 'Backend\CategoryController@apiIndexAttribute');
});


Route::prefix('administrator')->group(function () {
    Route::get('/', 'Backend\MainController@masterPage');
    Route::resource('categories', 'Backend\CategoryController');
    Route::get('categories/{id}/settings','Backend\CategoryController@indexSetting')->name('categories.indexSettings');
    Route::post('categories/{id}/settings','Backend\CategoryController@saveSetting');
    Route::resource('attributes-group', 'Backend\AttributeGroupController');
    Route::resource('attributes-value', 'Backend\AttributesValueController');
    Route::resource('brands','Backend\BrandsController');
    Route::resource('photos','Backend\PhotosController');
    Route::post('photos/upload','Backend\PhotosController@upload')->name('photos.upload');
    Route::resource('products','Backend\ProductController');

});

resources/views/admin/partials/category.blade.php
@if(isset($selected_category))
    @foreach($categories as $sub_category)
        <option class=" text-danger" value="{{$sub_category->id}}" @if($selected_category->parent_id == $sub_category->id)
        selected @endif >{{str_repeat('ــــ',$level)}} {{$sub_category->name}}</option>
        @if(count($sub_category->childrenRecursive) > 0)
            @include('admin.partials.category',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1 , 'selected_category'=>$selected_category])
        @endif
    @endforeach
@else
    @foreach($categories as $sub_category)
        <option class=" text-danger" value="{{$sub_category->id}}">{{str_repeat('ــــ',$level)}} {{$sub_category->name}}</option>
        @if(count($sub_category->childrenRecursive) > 0)
            @include('admin.partials.category',['categories'=>$sub_category->childrenRecursive,'level'=>$level+1])
        @endif
    @endforeach

@endif

resources/views/admin/partials/category_list.blade.php
@foreach($categories as $sub_category)
    <tr>
        <td><span class="text">{{$sub_category->id}}</span></td>
        <td><span class="text-danger">{{str_repeat('//ـــ' , $list_level)}} {{$sub_category->name}}</span></td>

        <div class="row">
            <td>
                <a class="btn btn-warning" href="{{route('categories.edit',$sub_category->id)}}">ویرایش</a>
                <div class="display_inline_block">
                    <form method="post" action="{{url('administrator/categories/'.$sub_category->id)}}">

                        {{@csrf_field()}}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-danger">حذف</button>
                        <a class="btn btn-primary" href="{{route('categories.indexSettings',$sub_category->id)}}">تنظیمات</a>
                    </form>
                </div>
            </td>

        </div>
    </tr>

    @if(count($sub_category->childrenRecursive) > 0)
        @include('admin.partials.category_list',['categories'=>$sub_category->childrenRecursive, 'list_level'=>$list_level+1])
    @endif
@endforeach

resources/views/admin/partials/form-errors.blade.php
@if (count($errors)>0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif